export const RETRIEVE_MODIFIERS = 'RETRIEVE_MODIFIERS';
export const SET_MODIFIERS = 'SET_MODIFIERS';
export const IMPORT_DOCUMENT = 'IMPORT_DOCUMENT';
export const EXPORT_DOCUMENT = 'EXPORT_DOCUMENT';
