export const SET_MODIFIERS = 'SET_MODIFIERS';

export const NEW_DOCUMENT = 'NEW_DOCUMENT';
export const LOAD_DOCUMENT = 'LOAD_DOCUMENT';
export const SAVE_DOCUMENT = 'SAVE_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';

export const SET_CURRENT_DOCUMENT = 'SET_CURRENT_DOCUMENT';

export const IMPORT_DOCUMENT = 'IMPORT_DOCUMENT';
export const IMPORT_DOCUMENT_SUCCESS = 'IMPORT_DOCUMENT_SUCCESS';
export const IMPORT_DOCUMENT_ERROR = 'IMPORT_DOCUMENT_ERROR';

export const EXPORT_DOCUMENT = 'EXPORT_DOCUMENT';
export const EXPORT_DOCUMENT_SUCCESS = 'EXPORT_DOCUMENT_SUCCESS';
export const EXPORT_DOCUMENT_ERROR = 'EXPORT_DOCUMENT_ERROR';
