export const RETRIEVE_MODIFIERS = 'RETRIEVE_MODIFIERS';
export const SET_MODIFIERS = 'SET_MODIFIERS';
export const IMPORT_DOCUMENT = 'IMPORT_DOCUMENT';
export const EXPORT_DOCUMENT = 'EXPORT_DOCUMENT';
export const SAVE_DOCUMENT = 'SAVE_DOCUMENT';
export const NEW_DOCUMENT = 'NEW_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const SET_DOCUMENT = 'SET_DOCUMENT';
